/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abd.p1.view;

import java.awt.event.ActionEvent;

import javax.swing.JOptionPane;

import abd.p1.controller.Controlador;

/**
 *
 * @author JuanluRomero
 */
public class DialogLogin extends javax.swing.JDialog {
	private static final long serialVersionUID = 1L;
	
	private Controlador c;
    /**
     * Creates new form DialogLogin
     */
    public DialogLogin(java.awt.Frame parent, boolean modal, Controlador c) {
        super(parent, modal);
        this.c = c;
        this.setLocation(300, 300);
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelEmail = new javax.swing.JLabel();
        labelPass = new javax.swing.JLabel();
        textFieldEmail = new javax.swing.JTextField();
        buttonAceptar = new javax.swing.JButton();
        buttonNuevo = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelEmail.setText("Direccion de correo:");

        labelPass.setText("Contraseña:");

        buttonAceptar.setText("Aceptar");
        buttonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldEmailActionPerformed(evt);
                if(c.loguear(textFieldEmail.getText(), new String(passwordField.getPassword()) ))  
                	dispose();
            }
        });

        buttonNuevo.setText("Nuevo usuario");
        buttonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNuevoActionPerformed(evt);
                String s = new String (passwordField.getPassword());
                if (!textFieldEmail.getText().equals("") && !s.equals("")){
                	
                	if (!c.existeUsuario(textFieldEmail.getText())){
                		//setVisible(false); boolean nuevo = true;
                		c.nuevoUsuario(textFieldEmail.getText(), new String(passwordField.getPassword()));
                	}
                	else
                		JOptionPane.showConfirmDialog(null, "Usuario ya existente", 
                    			"ERROR", JOptionPane.CLOSED_OPTION);
                }
                else{
                	JOptionPane.showConfirmDialog(null, "Debe introducirse un email y una contraseña", 
                			"ERROR", JOptionPane.CLOSED_OPTION);
                }
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonAceptar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelEmail)
                        .addComponent(labelPass)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(buttonNuevo)
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(passwordField))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail)
                    .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPass)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAceptar)
                    .addComponent(buttonNuevo))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void buttonNuevoActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub
		
	}

	protected void textFieldEmailActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub
		
	}

	/**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAceptar;
    private javax.swing.JButton buttonNuevo;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelPass;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField textFieldEmail;
    // End of variables declaration//GEN-END:variables
}
